### ISSUE TITLE
Plugin does not [render|"appear to work"]

### ISSUE THREAD

**Issue by DazWilkin** [weaveworks-plugins/scope-iowait#11]
Likely user error.

I am using Weave Scope out of interest so this should be considered very low priority.

```YAML
version: "3"

services:

  scope:
    image: weaveworks/scope:1.12.0
    container_name: scope
    network_mode: host
    pid: host
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/run/scope/plugins:/var/run/scope/plugins
    command:
      - "--probe.docker=true"
      - "--weave=false"

  iowait:
    image: weaveworksplugins/scope-iowait:latest
    container_name: iowait
    network_mode: host
    # pid: host
    # privileged: true
    volumes:
      - /var/run/scope/plugins/iowait:/var/run/scope/plugins/iowait
    command:
      - "--name=weaveworksplugins-scope-iowait"

  traffic-control:
    image: weaveworksplugins/scope-traffic-control:latest
    container_name: traffic-control
    network_mode: host
    # pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/scope/plugins/traffic-control:/var/run/scope/plugins/traffic-control
    command:
      - "--name=weaveworksplugins-scope-traffic-control"
```
And:
```bash
docker-compose logs scope
scope              | time="2019-12-31T01:19:13Z" level=info msg="publishing to: 127.0.0.1:4040"
scope              | <probe> INFO: 2019/12/31 01:19:13.856754 Basic authentication disabled
iowait             | 2019/12/31 01:19:13 Starting on hades-canyon...
traffic-control    | time="2019-12-31T01:19:14Z" level=info msg="Listening on: unix:///var/run/scope/plugins/traffic-control/traffic-control.sock" 
traffic-control    | time="2019-12-31T01:19:14Z" level=info msg=Listening... 
iowait             | 2019/12/31 01:19:13 Listening on: unix:///var/run/scope/plugins/iowait/iowait.sock
scope              | <app> INFO: 2019/12/31 01:19:13.914004 app starting, version 1.12.0, ID 377c4967c87efe5f
scope              | <app> INFO: 2019/12/31 01:19:13.914033 command line args: --mode=app --probe.docker=true --weave=false
scope              | <probe> INFO: 2019/12/31 01:19:13.914279 command line args: --mode=probe --probe.docker=true --weave=false
scope              | <probe> INFO: 2019/12/31 01:19:13.914306 probe starting, version 1.12.0, ID 463a8a95082320fb
scope              | <app> INFO: 2019/12/31 01:19:13.915036 Basic authentication disabled
scope              | <app> INFO: 2019/12/31 01:19:13.917395 listening on :4040
scope              | <probe> INFO: 2019/12/31 01:19:13.922940 Control connection to 127.0.0.1 starting
scope              | <probe> WARN: 2019/12/31 01:19:13.959443 Error setting up the eBPF tracker, falling back to proc scanning: error while loading map "maps/tcp_event_ipv4": operation not permitted
scope              | <probe> INFO: 2019/12/31 01:19:13.967994 Publish loop for 127.0.0.1 starting
scope              | <probe> INFO: 2019/12/31 01:19:18.962461 plugins: added plugin /var/run/scope/plugins/iowait/iowait.sock
scope              | <probe> INFO: 2019/12/31 01:19:18.962521 plugins: added plugin /var/run/scope/plugins/traffic-control/traffic-control.sock
```
And I can browse containers:
![image](https://user-images.githubusercontent.com/1022400/71606792-f5c16580-2b28-11ea-9340-9998c242e636.png)
The plugin lists as being installed (along with `traffic-control` which appears to work correctly). Even if I remove `traffic-control`, I see neither idle status nor the clock icon.

If I attempt to `/report` against the plugin:
```bash
sudo curl \
--silent \
--unix-socket /var/run/scope/plugins/iowait/iowait.sock \
--request GET http://localhost/report \
| jq .
{
  "Host": {
    "nodes": {
      "hades-canyon;<host>": {
        "metrics": {
          "idle": {
            "samples": [
              {
                "date": "2019-12-31T01:18:06.431290184Z",
                "value": 92.63
              }
            ],
            "min": 0,
            "max": 100
          }
        },
        "latestControls": {
          "switchToIOWait": {
            "timestamp": "2019-12-31T01:18:06.431318647Z",
            "value": {
              "dead": false
            }
          },
          "switchToIdle": {
            "timestamp": "2019-12-31T01:18:06.431318647Z",
            "value": {
              "dead": true
            }
          }
        }
      }
    },
    "metric_templates": {
      "idle": {
        "id": "idle",
        "label": "Idle",
        "format": "percent",
        "priority": 0.1
      }
    },
    "controls": {
      "switchToIOWait": {
        "id": "switchToIOWait",
        "human": "Switch to IO wait",
        "icon": "fa-clock-o",
        "rank": 1
      },
      "switchToIdle": {
        "id": "switchToIdle",
        "human": "Switch to idle",
        "icon": "fa-gears",
        "rank": 1
      }
    }
  },
  "Plugins": [
    {
      "id": "iowait",
      "label": "iowait",
      "description": "Adds a graph of CPU IO Wait to hosts",
      "interfaces": [
        "reporter",
        "controller"
      ],
      "api_version": "1"
    }
  ]
}
```
<strike>
Curiously, looking at the logs, `iowait` calls against `/report` with query parameters `api_version=1` and `probe_id=5904b3b98b2322e7`, if I curl that endpoint, the command appears (!?) to not complete correctly:

```bash
sudo curl --silent --unix-socket /var/run/scope/plugins/iowait/iowait.sock --request GET http://localhost/report?api_version=1&probe_id=5904b3b98b2322e7 | jq .
[1] 11666
{"Host":{"nodes":{"hades-canyon;\u003chost\u003e":{"metrics":{"idle":{"samples":[{"date":"2019-12-31T01:30:14.997970818Z","value":92.56}],"min":0,"max":100}},"latestControls":{"switchToIOWait":{"timestamp":"2019-12-31T01:30:14.997981726Z","value":{"dead":false}},"switchToIdle":{"timestamp":"2019-12-31T01:30:14.997981726Z","value":{"dead":true}}}}},"metric_templates":{"idle":{"id":"idle","label":"Idle","format":"percent","priority":0.1}},"controls":{"switchToIOWait":{"id":"switchToIOWait","human":"Switch to IO wait","icon":"fa-clock-o","rank":1},"switchToIdle":{"id":"switchToIdle","human":"Switch to idle","icon":"fa-gears","rank":1}}},"Plugins":[{"id":"iowait","label":"iowait","description":"Adds a graph of CPU IO Wait to hosts","interfaces":["reporter","controller"],"api_version":"1"}]}[1]+  Done                    sudo curl --silent --unix-socket /var/run/scope/plugins/iowait/iowait.sock --request GET http://localhost/report?api_version=1
```

The JSON returned is valid but it appears to not be closing the connection correctly.

If I make the request with either of the properties, command succeeds:
```bash
sudo curl \
--silent \
--unix-socket /var/run/scope/plugins/iowait/iowait.sock \
--request GET http://localhost/report?probe_id=5904b3b98b2322e7 \
| jq .
```
Or:
```bash
sudo curl \
--silent \
--unix-socket /var/run/scope/plugins/iowait/iowait.sock \
--request GET http://localhost/report?api_version=1 \
| jq .
```

Could this explain why the UI is also not working correctly?
</strike>
Ignore the <strike>above</strike>, that is user error in not enclosing the request string in `"..."`. Doing so, works as expected, e.g.:
```bash
sudo curl \
--silent \
--unix-socket /var/run/scope/plugins/iowait/iowait.sock \
--request GET \
"http://localhost/report?api_version=1&probe_id=5904b3b98b2322e7" \
| jq .
```
